# Generated by Django 5.1.5 on 2025-01-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_patrimonio', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(choices=[('Notebook', 'Notebook'), ('Desktop', 'Desktop')], max_length=50)),
                ('localidade', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=50)),
                ('data_ultima_avaliacao', models.DateField()),
                ('data_proxima_avaliacao', models.DateField()),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('mac_address_ethernet', models.CharField(blank=True, max_length=17)),
                ('mac_address_wifi', models.CharField(blank=True, max_length=17)),
                ('ip_fixado', models.GenericIPAddressField(blank=True, null=True)),
                ('bitlocker', models.BooleanField(default=False)),
                ('antivirus_licenca', models.CharField(blank=True, max_length=100)),
                ('antivirus_versao', models.CharField(blank=True, max_length=50)),
                ('bart_wazuh', models.BooleanField(default=False)),
                ('chrome_enterprise', models.BooleanField(default=False)),
                ('acesso_remoto_id', models.CharField(blank=True, max_length=50)),
                ('termo_custodia', models.BooleanField(default=False)),
            ],
        ),
    ]
