# Generated by Django 5.1.5 on 2025-01-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_alter_ativo_antivirus_licenca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='antivirus_licenca',
            field=models.CharField(choices=[('KASPERSKY ENDPOINT SECURITY FOR WINDOWS', 'KASPERSKY ENDPOINT SECURITY FOR WINDOWS'), ('MICROSOFT DEFENDER FOR ENDPOINT', 'MICROSOFT DEFENDER FOR ENDPOINT')], default='KASPERSKY ENDPOINT SECURITY FOR WINDOWS', max_length=100),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='ip_fixado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='status',
            field=models.CharField(choices=[('Operacional', 'Operacional'), ('Estoque', 'Estoque'), ('Reservado', 'Reservado')], default='Operacional', max_length=50),
        ),
    ]
